name: Bats

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  run:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: bats-core/bats-action@4.0.0
        with:
          support-install: false
          assert-install: false
          detik-install: false
          file-install: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: bats test/
