name: Bats

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bats-core/bats-action@4.0.0
        with:
          support-install: false
          assert-install: false
          detik-install: false
          file-install: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run
        run: bats test/
