name: Lychee

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .lycheecache
          key: lychee-cache-${{ hashFiles('README.md', 'dot_config/zellij/config.kdl') }}
          restore-keys: lychee-cache-
      - uses: lycheeverse/lychee-action@v2.8.0
        with:
          args: '--cache --retry-wait-time 5 README.md dot_config/zellij/config.kdl'
